name: API Tests Workflow

on:
  push:
    branches:
      - feature/api-tests
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      API_KEY: ${{ secrets.API_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Run Tests
        run: |
          cd Github_api_Automation_Framework
          mvn clean test

      - name: Upload API Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-test-report
          path: Github_api_Automation_Framework/apireports/

  deploy-report:
    needs: test
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy Report
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: Github_api_Automation_Framework/apireports
